### ISSUE TITLE
Can't Customize the CSS code

### ISSUE THREAD

**Issue by mohanak57** [ABD-dev/ngx-twitter-timeline#10]
I tried to set height for - .timeline-Viewport class but its not working
.SandboxRoot.var-fully-expanded .timeline-Viewport {
    height: 400px
}

**Comment by featured14** [comment]
Twitter timeline runs in an iframe element. You can not customise classes in CSS like that.
The only solution (not tested) is to manipulate the iframe css from within JS, trying to insert a custom css file.
Just a hint/starting point:
```
var cssLink = document.createElement("link");
cssLink.href = "style.css"; 
cssLink.rel = "stylesheet"; 
cssLink.type = "text/css"; 
frames['twitter-widget-0'].document.head.appendChild(cssLink);
```
