### ISSUE TITLE
Which API URLs does the app call?

### ISSUE THREAD

**Issue by n0490b** [ABD-dev/ngx-twitter-timeline#11]
I am trying to use this in my Ionic app but I am forced to whitelist URLs that the app can call... Currently I have to whitelist all URLs to use this library. Can I get a list of API urls that are called by this library so I can white list them?

**Comment by featured14** [comment]
Whitelist ```platform.twitter.com```  as it tries to get ```https://platform.twitter.com/widgets.js```
