### ISSUE TITLE
Tweet Disappears in Mat-Tab

### ISSUE THREAD

**Issue by muralimanoharm** [ABD-dev/ngx-twitter-timeline#12]
I am using" ngx-twitter-timeline" in my web page which is written in angular 6. I am trying to create a Mat-tab in my page and one of the tab has this twitter embed. 
<mat-tab>
  <ngx-twitter-timeline [data]="{sourceType: 'url', url: 'someTwitterUrl" [opts]="{tweetLimit: 5}"></ngx-twitter-timeline>
</mat-tab>

When i load the page for the first time it is working fine. But if i go to the next tab and  get back to this twitter tab the tweets are disappeared. 

Kindly help me to resolve this.

**Comment by featured14** [comment]
Here is one solution for that:
```
<mat-tab-group>
  <mat-tab label="First"> Content 1 </mat-tab>
  <mat-tab label="Second">
    <ng-template matTabContent>
        <ngx-twitter-timeline
          [data]="{sourceType: 'url', url: 'https://twitter.com/twitterdev'}"
          [opts]="{tweetLimit: 5}"
        ></ngx-twitter-timeline>
    </ng-template>
  </mat-tab>
  <mat-tab label="Third"> Content 3 </mat-tab>
</mat-tab-group>
```
