### ISSUE TITLE
Is this dead? angular 6

### ISSUE THREAD

**Issue by danner26** [ABD-dev/ngx-twitter-timeline#13]
Is this repo getting updated still or is it dead? I notice there has been a issue open for a while with no comments or anything.

I would like to have this updated for Angular 6, #6 

It shouldn't be hard to update this, but I also see the PR #8 has been open for a while as well

If you are not looking to keep this updated, I would be happy to take over.

**Comment by featured14** [comment]
I will take my time to update the repo and use the latest angular this weekend.

**Comment by danner26** [comment]
Great, please let us know when that is done! Thank you. 

Also, if you would like any help let me know.

**Comment by featured14** [comment]
Update to Angular 7, using angular cli library generator.

**Comment by danner26** [comment]
Great, thank you!
