### ISSUE TITLE
Not working with angular 6

### ISSUE THREAD

**Issue by jubinpolackal** [ABD-dev/ngx-twitter-timeline#6]
I am getting the following error while used with Angular 6: -

ERROR in node_modules/ngx-twitter-timeline/twitter-timeline.service.d.ts(1,10): error TS2305: Module '"/home/xxxx/Documents/Projects/xxxx/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
Could you please suggest me a solution?

**Comment by featured14** [comment]
Try `npm install rxjs-compat --save`

**Comment by amareshb** [comment]
Yup, that works. @jubinpolackal

**Comment by andlewis** [comment]
Any plans for an upgrade to rxjs 6, so we don't have to use the compatibility shim?

**Comment by nestorg85** [comment]
To use with rxjs 6, change all import lines   from 'rxjs/Observable' to 'rxjs'. This worked for me. 
Yo can found it in index.js and twitter-timeline.service files
