### ISSUE TITLE
How to use this for hashtags

### ISSUE THREAD

**Issue by amareshb** [ABD-dev/ngx-twitter-timeline#7]
I am trying to embed hashtags into it. And i see the following error:

Unhandled Promise rejection: this.params.dataSource.fetch is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: this.params.dataSource.fetch is not a function

@ABD-dev Need help on this

**Comment by j-langlois** [comment]
The embedded twitter feed does not support queries such as hashtag. 
See supported use cases [here](https://help.twitter.com/en/using-twitter/embed-twitter-feed)

[Staff said](https://twittercommunity.com/t/embed-live-search-results-for/103705/3#post_4) they don't plan tu support it either 
> And we don’t have any plans to support embedding hashtag Timeline widgets in publish.twitter.com

**Comment by amareshb** [comment]
@j-langlois I read that. Thanks for the response though.
